//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsimSehirHayvan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsimSehirHayvan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abay
        ///Abayhan
        ///Abbas
        ///Abdal
        ///Abdi
        ///Abdullah
        ///Abdurrahman
        ///Abdülâlim
        ///Abdülazim
        ///Abdülaziz
        ///Abdülbaki
        ///Abdülbari
        ///Abdülbasir
        ///Abdülbasit
        ///Abdülcabbar
        ///Abdülcebbar
        ///Abdülcelil
        ///Abdülcemal
        ///Abdülcevat
        ///Abdülezel
        ///Abdülferit
        ///Abdülfettah
        ///Abdülgaffar
        ///Abdülgaffur
        ///Abdülgafur
        ///Abdülgani
        ///Abdülhadi
        ///Abdülhak
        ///Abdülhakim
        ///Abdülhalik
        ///Abdülhalim
        ///Abdülhamit
        ///Abdülkadir
        ///Abdülkahhar
        ///Abdülkerim
        ///Abdüllâtif
        ///Abdülmecit
        ///Abdülmelik
        ///Abdülmennan
        ///Abdülmetin
        ///Abdülnasır
        ///Abdülvahap
        ///Abdülvahit
        ///Abdürrahim
        ///Abdürrahman
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isimler {
            get {
                return ResourceManager.GetString("isimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adana
        ///Adıyaman
        ///Afyonkarahisar
        ///Ağrı
        ///Aksaray
        ///Amasya
        ///Ankara
        ///Antalya
        ///Ardahan
        ///Artvin
        ///Aydın
        ///Balıkesir
        ///Bartın
        ///Batman
        ///Bayburt
        ///Bilecik
        ///Bingöl
        ///Bitlis
        ///Bolu
        ///Burdur
        ///Bursa
        ///Çanakkale
        ///Çankırı
        ///Çorum
        ///Denizli
        ///Diyarbakır
        ///Düzce
        ///Edirne
        ///Elazığ
        ///Erzincan
        ///Erzurum
        ///Eskişehir
        ///Gaziantep
        ///Giresun
        ///Gümüşhane
        ///Hakkâri
        ///Hatay
        ///Iğdır
        ///Isparta
        ///İstanbul
        ///İzmir
        ///Kahramanmaraş
        ///Karabük
        ///Karaman
        ///Kars
        ///Kastamonu
        ///Kayseri
        ///Kilis
        ///Kırıkkale
        ///Kırklareli
        ///Kırşehir
        ///Kocaeli
        ///Konya
        ///Kütahya
        ///Malatya
        ///Manisa
        ///Mardin
        ///Mer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sehirler {
            get {
                return ResourceManager.GetString("sehirler", resourceCulture);
            }
        }
    }
}
